### ISSUE TITLE
[Documentation] Create introductory texts to API

### ISSUE THREAD

**Issue by luabida** [Mosqlimate-project/Data-platform#73]
Pages in which require description:
- Home page https://api.mosqlimate.org/
- About page https://api.mosqlimate.org/about/

**Comment by fccoelho** [comment]
Here is a new version of content for the Model registry page, @luabida:


## Model Registry
The model registry is a tool for registering forecasting models that want to share their  predictions in the Mosqlimate platform.

As with everything in our API, the model registry can be accessed programatically. You can send [insert new models](https://api.mosqlimate.org/docs/registry/POST/models/) in the platform, or [post predictions](https://api.mosqlimate.org/docs/registry/POST/predictions/) generated from a registered model.

Posted predictions will be available for visualization alongside data, in our platforms dashboard.

**Comment by fccoelho** [comment]
It may be worth to include a screenshot of the form in the page

**Comment by fccoelho** [comment]
Texto para a pagina predictions:

## Predictions
In order to register a prediction, you need at least two pieces of information before you can use the code examples below. The first is the `id` number of your model, which you can obtain [here](https://api.mosqlimate.org/models/). The second is the commit id of the exact version of your code (the model must be available on a Github reposotory) that has generated the predictions. in order to find out this you can use the following code in the (Linux or Mac) terminal:

```bash
git show | sed -n '1p' | sed 's/commit \(.*\)/\1/'
``` 

If you use Windows, you can [install WSL](https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-11-with-gui-support#1-overview).

The prediction itself, must be provided as a JSON object. Please refer to our visualization documentation examples.

**Comment by fccoelho** [comment]
@luabida in the Datastore API structure as well as the documentation structure, I want to change the names of the endpoints:

- Historico_alerta -> infodengue
- Copernicus_Brasil -> climate
- contaovos -> mosquito

**Comment by eduardocorrearaujo** [comment]
On the homepage, the first paragraph says that we will have arbovirus and climate data, while the second says we will have only arbovirus data. I think we could replace the second paragraph by: 

Currently, only data for the arboviruses: dengue, chikungunya, and zika and climate data fetch from [Copernicus project](https://cds.climate.copernicus.eu/#!/home)  are available through this platform. By now, we have the data for all cities in Brazil between 2010 and 2023. More datasets will be made available in time. All the available data are in the public domain and are official data made available by the Brazilian Ministry of Health.

and the third paragraph: 

The purpose of this platform is to enhance the comparability of forecasting models by making it possible for all models to learn from the same data. So, we have a  model registry API open to anyone willing to contribute. It only requires creating a user account first. Once done, you can register your models and predictions and compare your model's performance with others saved in the API. The Mosqlimate project reserves the right to curate the model collection and decide which one to make available through the platform.

**Comment by fccoelho** [comment]
Done
