### ISSUE TITLE
Error: relation "Historico_alerta" does not exist

### ISSUE THREAD

**Issue by esloch** [Mosqlimate-project/Data-platform#86]
**Description:**
When running the test case in `test_queries_database.py`, the following error occurred:

```
Traceback (most recent call last):
  File "/opt/services/mosqlimate/datastore/tests/test_queries_database.py", line 18, in test_get_data
    HistoricoAlerta.objects.create(
  ...
django.db.utils.ProgrammingError: relation "Historico_alerta" does not exist
LINE 1: INSERT INTO "Historico_alerta" ("data_iniSE", "SE", "casos_e...
---
```

**Comment by luabida** [comment]
This error is expected, since the Historico_alerta model is configured with `managed = False`. This option tells django the table to populate the objects is read only, therefore it won't perform any database operation besides queries. Reference: https://docs.djangoproject.com/en/4.2/ref/models/options/#managed
